# Generated by Django 4.2 on 2024-10-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_status', models.CharField(choices=[('pr', 'Processing'), ('sh', 'Shipping'), ('ar', 'Arrived')], max_length=20)),
                ('date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pd', 'Paid'), ('pg', 'Pending'), ('cn', 'Canceled')], max_length=20)),
                ('region', models.CharField(choices=[('UA', 'ua'), ('EU', 'eu')], default='ua', max_length=3)),
                ('city', models.CharField(default='default', max_length=20)),
                ('shipment_address', models.CharField(default='default', max_length=20)),
                ('name', models.CharField(default='default', max_length=20)),
                ('surname', models.CharField(default='default', max_length=20)),
                ('lastname', models.CharField(blank=True, default='default', max_length=20)),
                ('phonenum', models.CharField(default='default', max_length=20)),
                ('stripe_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_sub_id', models.CharField(blank=True, max_length=60)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('last_paid', models.DateField(blank=True, null=True)),
                ('next_payment_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('trialing', 'Trialing')], default='active', max_length=10)),
                ('region', models.CharField(choices=[('UA', 'ua'), ('EU', 'eu')], default='UA', max_length=3)),
                ('city', models.CharField(default='default', max_length=20)),
                ('shipment_address', models.CharField(default='default', max_length=20)),
                ('name', models.CharField(default='default', max_length=20)),
                ('surname', models.CharField(default='default', max_length=20)),
                ('lastname', models.CharField(blank=True, default='default', max_length=20)),
                ('phonenum', models.CharField(default='default', max_length=20)),
                ('delivery_reference', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_item', to='order.subscription')),
            ],
        ),
    ]
